### ISSUE TITLE
Problem with the result of get_edges

### ISSUE THREAD

**Issue by misan** [Huangtingting93/Trace_outline#1]
Hi, 

First of all, thanks for sharing the code and example. I was giving it a go with Python 3.9 and I am getting this error
`    edge_arr = np.vstack((np.asarray(edges_list)))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1889,) + inhomogeneous part.`

the edge_list variable looks like this
`[array([[ 0, 72],
       [ 0,  3],
       [ 0,  7]], dtype=int64), array([[ 1, 81],
       [ 1, 74],
       [ 1,  4]], dtype=int64), array([[ 2, 75],
       [ 2, 71]], dtype=int64), array([[ 0,  3],
       [ 3,  7],.......`

That is with the bunny example pasted from the Jupiter book to a Python file.

Maybe I messed it up in the process ... ?

**Comment by misan** [comment]
Solution: change to 'edge_arr = np.vstack(edges_list)' where you had 'edge_arr = np.vstack((np.asarray(edges_list)))'

**Comment by Huangtingting93** [comment]
changed the code as suggested.
